/** Privacy-safe defaults for optional product analytics. */
export const TELEMETRY_ENABLED_ON_STATUS_FAILURE = false;

export const MIXPANEL_PROPERTY_BLACKLIST = Object.freeze([
  "$current_url",
  "$initial_referrer",
  "$initial_referring_domain",
  "$referrer",
  "$referring_domain",
  "$search_engine",
  "current_domain",
  "current_page_title",
  "current_url_path",
  "current_url_protocol",
  "current_url_search",
  "dclid",
  "fbclid",
  "gclid",
  "initial_utm_campaign",
  "initial_utm_campaign_id",
  "initial_utm_content",
  "initial_utm_creative_format",
  "initial_utm_id",
  "initial_utm_marketing_tactic",
  "initial_utm_medium",
  "initial_utm_source",
  "initial_utm_source_platform",
  "initial_utm_term",
  "ko_click_id",
  "li_fat_id",
  "mp_keyword",
  "msclkid",
  "sccid",
  "ttclid",
  "twclid",
  "utm_campaign",
  "utm_campaign_id",
  "utm_content",
  "utm_creative_format",
  "utm_id",
  "utm_marketing_tactic",
  "utm_medium",
  "utm_source",
  "utm_source_platform",
  "utm_term",
  "wbraid",
]);

export const MIXPANEL_PRIVACY_DEFAULTS = Object.freeze({
  track_pageview: false,
  autocapture: false,
  property_blacklist: MIXPANEL_PROPERTY_BLACKLIST,
  save_referrer: false,
  store_google: false,
  stop_utm_persistence: true,
  track_marketing: false,
  // Session replay is a separate, high-sensitivity feature and is never
  // enabled implicitly with ordinary product analytics.
  record_sessions_percent: 0,
  record_mask_text_selector: "*",
  record_block_selector: "[data-telemetry-block], [data-private], canvas",
  record_collect_fonts: false,
  record_canvas: false,
});
